'use strict';
const gate=document.getElementById('gate'), app=document.getElementById('app'), form=document.getElementById('unlock'), statusEl=document.getElementById('gate-status');
let trip=null, ticketKey=null, activeDay=0, activeView='days', sessionChecks=new Set();
const ticketUrls=new Map();
const isDone=a=>Boolean(a.done)||sessionChecks.has(a.id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const euros=v=>typeof v==='number'?new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(v):'See options';
const safeUrl=u=>{try{const x=new URL(u);return ['https:','http:'].includes(x.protocol)?x.href:'#';}catch{return '#';}};
const link=(u,label,cls='')=>`<a class="${cls}" href="${esc(safeUrl(u))}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;
const sourceLinks=urls=>`<div class="stop-links">${[...new Set(urls||[])].map((u,i)=>link(u,i===0?'Official / booking page':`Source ${i+1}`)).join('')}</div>`;
const mapLink=place=>link('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(place),'Open map');
const journeyLink=(from,to)=>link('https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(from)+'&destination='+encodeURIComponent(to)+'&travelmode=transit','Transit directions');
const paras=t=>String(t||'').split('\n').map(x=>`<p>${esc(x)}</p>`).join('');
const decode=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const checklistGroups=[
  {key:'urgent',title:'Urgent — book now',badge:'URGENT',intro:'Start here. These bookings depend on limited ticket or train availability. Check the current slot and final price before paying.',ids:['action-1','action-2','action-4','action-5','action-6','action-7','action-12']},
  {key:'release',title:'Time-sensitive — book when released',badge:'RELEASE WINDOW',intro:'These need prompt action on the date shown. They cannot necessarily be reserved today; set a reminder now.',ids:['action-8','action-14']},
  {key:'prepare',title:'Important — before departure',badge:'BEFORE DEPARTURE',intro:'Complete these before traveling. Confirm accommodation and travel documents, reserve meals and the airport pickup, and prepare transport and offline tickets.',ids:['action-3','action-21','action-22','action-23','action-9','action-10','action-11','action-18','action-15']},
  {key:'optional',title:'Optional — decide during the trip',badge:'OPTIONAL',intro:'These are choices, not required bookings. Prices are retained for comparison and excluded from the base budget.',ids:['action-24']},
  {key:'later',title:'Later — during the trip',badge:'LATER',intro:'Do these at the time indicated. Weather and service checks are most useful close to departure; they do not need to delay the urgent bookings above.',ids:['action-13','action-16','action-17','action-19','action-20']}
];
function checklistHtml(items){
  const knownIds=new Set(checklistGroups.flatMap(g=>g.ids));
  const groups=[{key:'booked',title:'Booked — tickets ready',badge:'BOOKED',intro:'Confirmed purchases. Open My tickets to view or download the original admission PDFs.',ids:items.filter(a=>a.done).map(a=>a.id)},...checklistGroups,{key:'other',title:'Other preparation',badge:'TO DO',intro:'Review these additional tasks.',ids:items.filter(a=>!knownIds.has(a.id)).map(a=>a.id)}];
  return groups.map(g=>{const actions=g.ids.map(id=>items.find(a=>a.id===id)).filter(a=>a&&(g.key==='booked'||!a.done));return actions.length?`<section class="check-group priority-${g.key}" aria-labelledby="priority-${g.key}"><div class="check-group-heading"><h3 id="priority-${g.key}">${esc(g.title)}</h3><span class="group-progress" data-group-progress="${g.key}"></span></div><p>${esc(g.intro)}</p><div class="checks">${actions.map(a=>`<label class="check"><input type="checkbox" data-check="${esc(a.id)}" ${isDone(a)?'checked':''} ${a.done?'disabled':''}><span><span class="check-badges"><span class="tag priority-tag">${g.key==='urgent'&&a.id==='action-3'?'URGENT · BOOKING DEPENDENCY':esc(a.done?'BOOKED':g.badge)}</span><span class="check-timing">${esc(a.urgency)}</span></span><strong>${esc(a.title)}</strong>${a.costLabel?`<p class="check-price">${esc(a.costLabel)}</p><p class="small">${esc(a.priceDetail)}</p>`:""}<p>${esc(a.detail)}</p>${a.availability?`<p class="check-status"><b>Availability:</b> ${esc(a.availability)}</p>`:""}${a.queueBenefit?`<p class="small"><b>Queues:</b> ${esc(a.queueBenefit)}</p>`:""}${sourceLinks(a.sourceUrls)}</span></label>`).join('')}</div></section>`:'';}).join('');
}
form.addEventListener('submit',async e=>{
  e.preventDefault();const input=document.getElementById('password'),button=document.getElementById('unlock-button');button.disabled=true;statusEl.textContent='Opening your guide…';
  try{
    if(!globalThis.crypto?.subtle)throw new Error('secure');
    const response=await fetch('payload.json',{cache:'no-store'});if(!response.ok)throw new Error('network');
    const payload=await response.json();const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(input.value),'PBKDF2',false,['deriveKey']);
    const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:decode(payload.salt),iterations:payload.iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['decrypt']);
    const plaintext=await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(payload.iv)},key,decode(payload.data));
    trip=JSON.parse(new TextDecoder().decode(plaintext));ticketKey=key;input.value='';statusEl.textContent='';
    const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
    const matched=trip.days.findIndex(d=>d.date===today);activeDay=matched<0?0:matched;
    try{sessionChecks=new Set(JSON.parse(localStorage.getItem('paris-guide-checks-v1')||'[]'));}catch{sessionChecks=new Set();}
    render();gate.hidden=true;app.hidden=false;document.getElementById('app-title').focus();
  }catch(error){trip=null;statusEl.textContent=error.message==='secure'?'Open the HTTPS website in a current browser to unlock.':error.message==='network'?'The guide could not load. Check your connection and try again.':'That password did not open the guide. Please try again.';}finally{button.disabled=false;}
});
function stopHtml(s,index,day){const photo=s.photo?`<figure class="activity-photo"><img src="${esc(safeUrl(s.photo.url))}" alt="${esc(s.photo.alt)}" width="320" height="240" loading="lazy" decoding="async"><figcaption>${s.photo.caption?`<span>${esc(s.photo.caption)}</span>`:''}${link(s.photo.source,s.photo.credit||'Photo source')}<span>Cropped for display</span></figcaption></figure>`:'';return `<article class="stop"><time>${esc(s.time)}</time><div class="stop-card"><h3>${esc(s.title)}</h3><div class="stop-content"><div>${paras(s.body)}${s.transfer?`<p class="transfer">${esc(s.transfer)}</p>`:''}<div class="stop-links">${s.place?mapLink(s.place):''}${s.url?link(s.url,'Details / tickets'):''}${s.place&&index===0?journeyLink(trip.home,s.place):''}</div></div>${photo}</div></div></article>`;}
function dayHtml(d){return `<div class="day-layout"><div><div class="day-header"><span class="eyebrow">${esc(d.short)} · ${esc(d.leave)}</span><h2>${esc(d.title)}</h2><p>${esc(d.theme)}</p><div class="stats"><span>${esc(d.pace)}</span><span>${esc(d.walking)}</span></div></div><div class="timeline">${d.stops.map((s,i)=>stopHtml(s,i,d)).join('')}</div></div><aside><section class="side-card accent"><h3>Before you set off</h3><ul>${d.advice.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="side-card"><h3>If something changes</h3>${paras(d.fallback)}</section><section class="side-card"><h3>Weather plan</h3>${paras(d.weather)}</section><section class="side-card"><h3>Home base</h3><p>${esc(trip.home)}</p>${mapLink(trip.home)}<p class="small">All times here are Paris local. Check live directions before leaving.</p></section></aside></div>`;}
function ticketHtml(t){return `<article class="detail-card"><div class="ticket-top"><div><span class="tag">${esc(t.date||'Flexible')}${t.time?' · '+esc(t.time):''}</span><h3>${esc(t.name)}</h3></div><div class="price">${euros(t.familyPrice)}<small>family of four</small></div></div><p><strong>${esc(t.recommended)}</strong></p><p>${esc(t.availability)}</p><p><strong>Entry:</strong> ${esc(t.reservation)}</p><p><strong>Queues:</strong> ${esc(t.queueBenefit)}</p><p class="small">${esc(t.risk)}</p>${t.alternatives?.length?`<details><summary>Compare alternatives</summary>${t.alternatives.map(a=>`<p><strong>${esc(a.name)}${a.familyPrice!==null&&a.familyPrice!==undefined?' · '+euros(a.familyPrice):''}</strong><br>${esc(a.status)}</p>`).join('')}</details>`:''}${sourceLinks(t.sourceUrls)}</article>`;}
function foodHtml(f){return `<article class="detail-card"><span class="tag">${esc(f.noEggConfidence)}</span><h3>${esc(f.name)}</h3><p class="meta">${esc(f.address)}</p><p><strong>Order:</strong> ${esc(f.signatureChoices)}</p><p><strong>Hours:</strong> ${esc(f.hours)}</p><p><strong>Budget:</strong> ${esc(f.price)}</p>${f.reservations?`<p><strong>Planning:</strong> ${esc(f.reservations)}</p>`:''}<p class="small">${esc(f.basis||'')} ${esc(f.caveats)}</p><div class="stop-links">${mapLink(f.address)}${f.officialUrl?link(f.officialUrl,'Restaurant website'):''}</div>${sourceLinks(f.sourceUrls)}</article>`;}
function facts(rows){return `<dl class="facts">${rows.map(([a,b])=>`<dt>${esc(a)}</dt><dd>${esc(b)}</dd>`).join('')}</dl>`;}
function sourceNotes(text){return esc(text).replace(/https?:\/\/[^\s<>"&]+/g,u=>{const clean=u.replace(/[).,;]+$/,'');return `<a href="${clean}" target="_blank" rel="noopener noreferrer">${clean}</a>${u.slice(clean.length)}`;});}
function render(){const r=trip.reference;app.innerHTML=`
  <header class="topbar"><span class="brand">PARIS / EN FAMILLE</span><div class="top-tools"><button data-view="wallet">My tickets</button>${link(trip.wanderlog,'Open Wanderlog')}<button id="print">Print / save PDF</button><button id="lock">Lock</button></div></header>
  <main class="shell"><section class="intro"><div><span class="eyebrow">${esc(trip.dates)}</span><h1 id="app-title" tabindex="-1">${esc(trip.title)}</h1><p>${esc(trip.intro)}</p><div class="home-plan-link">${link(trip.wanderlog,'Open this trip in Wanderlog ↗','button wanderlog-button')}</div><div class="pills"><span class="pill">${esc(trip.family)}</span><span class="pill">${esc(trip.diet)}</span></div></div><img src="${esc(trip.hero)}" alt="Eiffel Tower beside the Seine in Paris" width="700" height="360"></section>
  <nav class="section-tabs" aria-label="Guide sections" role="tablist">${[['days','Day by day'],['wallet','My tickets'],['tickets','Tickets & prices'],['checklist','To book & prepare'],['food','Eat egg-free'],['travel','Stay & transport'],['research','Sources & decisions']].map(([id,name])=>`<button id="tab-${id}" role="tab" aria-controls="view-${id}" aria-selected="${activeView===id}" data-view="${id}">${name}</button>`).join('')}</nav>
  <section id="view-days" class="view" role="tabpanel" aria-labelledby="tab-days" ${activeView!=='days'?'hidden':''}><div class="notice">${esc(trip.alert)}</div><nav class="days" aria-label="Choose a day" role="tablist">${trip.days.map((d,i)=>`<button class="day-tab" id="day-tab-${i}" role="tab" aria-controls="day-content" data-day="${i}" aria-selected="${i===activeDay}"><strong>${esc(d.short)}</strong><span>${esc(d.name)}</span></button>`).join('')}</nav><div id="day-content" role="tabpanel" aria-labelledby="day-tab-${activeDay}">${dayHtml(trip.days[activeDay])}</div><div class="print-only">${trip.days.map(dayHtml).join('')}</div></section>

  <section id="view-wallet" class="view" role="tabpanel" aria-labelledby="tab-wallet" ${activeView!=='wallet'?'hidden':''}>
    <h2>Your booked tickets</h2><p>Original admission PDFs for confirmed purchases. All times are Paris local.</p>
    <div class="notice">Download both PDFs to your phone before leaving home, then check that each opens offline. Each PDF contains four tickets. Downloaded files remain on your device after you lock this guide.</div>
    <div class="wallet-total">${(trip.bookings||[]).length} confirmed bookings · ${euros((trip.bookings||[]).reduce((sum,b)=>sum+b.paid,0))} paid</div>
    <div class="grid">${(trip.bookings||[]).map(b=>`<article class="detail-card wallet-card"><div class="ticket-top"><div><span class="tag booked-tag">BOOKED · PAID</span><h3>${esc(b.name)}</h3><p class="wallet-date">${esc(b.date)} · ${esc(b.time)}</p></div><div class="price">${euros(b.paid)}<small>${b.quantity} tickets</small></div></div><p><strong>Names:</strong> ${esc(b.holders)}</p><p><strong>Order:</strong> ${esc(b.reference)}</p><p>${esc(b.arrival)}</p><div class="wallet-actions"><button data-ticket="${esc(b.id)}" data-mode="view">Open ticket PDF</button><button data-ticket="${esc(b.id)}" data-mode="download">Download for offline</button></div><p class="small" id="ticket-status-${esc(b.id)}" role="status"></p><p class="small">${esc(b.notes)}</p><div class="stop-links">${link(b.emailUrl,'Confirmation email')}${link(b.manageUrl,'Official order account')}</div></article>`).join('')}</div>
  </section>
  <section id="view-tickets" class="view" role="tabpanel" aria-labelledby="tab-tickets" ${activeView!=='tickets'?'hidden':''}><h2>The right ticket for each stop</h2><p>Prices below apply to your four travelers. Louvre and Versailles are booked; their original PDFs are in My tickets. Other prices remain planning quotes until you purchase.</p><div class="budget"><div><span>Selected Paris + Versailles sights</span><strong>${euros(trip.budget.attractions)}</strong></div><div><span>Giverny day including travel</span><strong>${euros(trip.budget.giverny)}</strong></div><div><span>City passes + two airport taxis</span><strong>${euros(trip.budget.cityTransport)}</strong></div></div><div class="notice">${esc(trip.budget.note)}</div><div class="grid">${r.tickets.map(ticketHtml).join('')}</div></section>
  <section id="view-checklist" class="view" role="tabpanel" aria-labelledby="tab-checklist" ${activeView!=='checklist'?'hidden':''}><h2>To book & prepare, by priority</h2><p>This is the booking and preparation checklist for the current itinerary. Work through the red urgent items first, then follow the release dates and preparation sections below.</p><p>Prices are for the family of four. Included costs are not charged twice; variable or unquoted costs are labeled. Availability is a dated observation, not a hold. Tick items after you finish them. Checkmarks stay on this device; they do not reserve anything or sync with your family.</p><div id="check-progress" class="progress" role="status"></div>${checklistHtml(r.actionItems)}</section>
  <section id="view-food" class="view" role="tabpanel" aria-labelledby="tab-food" ${activeView!=='food'?'hidden':''}><h2>Good food, without eggs</h2><div class="notice"><p>${esc(trip.dietExplanation)}</p><p class="diet-phrase">${esc(trip.dietPhrase)}</p></div><p>Fully vegan places are the easiest choices. For mixed or vegetarian kitchens, order a specifically vegan dish or ask staff to confirm ingredients. Prices are menu observations or clearly marked estimates, not table quotes.</p><div class="food-grid">${[...r.restaurants,...r.bakeriesAndFamousCafe].map(foodHtml).join('')}</div></section>
  <section id="view-travel" class="view" role="tabpanel" aria-labelledby="tab-travel" ${activeView!=='travel'?'hidden':''}><h2>Your stay & getting around</h2><div class="grid"><article class="detail-card wide"><h3>Your apartment</h3>${facts(trip.travel.lodging)}<div class="actions">${mapLink(trip.home)}${link('https://www.airbnb.com/trips','Open Airbnb trips','button')}</div></article><article class="detail-card"><h3>Arrival · September 14</h3>${facts(trip.travel.arrival)}</article><article class="detail-card"><h3>Departure · September 19</h3>${facts(trip.travel.departure)}</article>${r.transit.map(t=>`<article class="detail-card"><h3>${esc(t.name)}</h3><p>${esc(t.description)}</p><p><strong>Set up:</strong> ${esc(t.setup)}</p><p><strong>Choice:</strong> ${esc(t.decision)}</p><p class="small">${esc(t.caveats)}</p>${sourceLinks(t.sourceUrls)}</article>`).join('')}<article class="detail-card wide"><h3>Small things that help</h3><p>Keep passport copies and tickets available offline; carry the original ID for age discounts and membership cards. Use a contactless card and a little cash for small purchases. France uses 230V Type E sockets; check your device charger rating and bring suitable adapters. Keep bags closed on the Métro and around busy attractions.</p><p>Emergency number: 112. For flight, rail or weather disruption, recheck the operator’s live status before setting off. Carry water, a light jacket and comfortable shoes; the apartment and several attractions have stairs.</p></article></div></section>
  <section id="view-research" class="view" role="tabpanel" aria-labelledby="tab-research" ${activeView!=='research'?'hidden':''}><h2>Why this route works</h2><div class="side-card"><ul>${trip.planningNotes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul></div><h3>Useful alternatives that did not make the main route</h3><div class="grid">${r.exclusions.map(x=>`<article class="detail-card"><h4>${esc(x.name)}</h4><p>${esc(x.reason)}</p>${sourceLinks(x.sourceUrls)}</article>`).join('')}</div><h3>Source record</h3><p>Research checked ${esc(trip.checked)}. Each ticket, restaurant and transport card links to its sources. The expandable notes preserve the fuller comparison and live-check details; the day-by-day guide above reflects the latest corrections.</p><p>${link(r.articleInfluence.url,'Your suggested Dangerous Business article')} · ${esc(r.articleInfluence.summary)}</p>${trip.research.map(n=>`<details><summary>${esc(n.title)}</summary><div class="raw-note">${sourceNotes(n.text)}</div></details>`).join('')}<details><summary>About the password protection</summary><p>The public site contains encrypted itinerary data. The browser derives a key from your password and decrypts the guide locally; the password and decrypted trip are not saved by the guide. The device stores only checklist item IDs. Lock or close this tab when finished on a shared device. Anyone with the password can read the full itinerary. Printing or saving a PDF creates an unencrypted copy.</p>${link('https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveKey','Web Crypto documentation')} · ${link('https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site','GitHub Pages hosting')}</details></section>
  <footer class="footer">Research checked ${esc(trip.checked)} · ${link(trip.wanderlog,'New private Wanderlog plan')} · ${link(trip.original,'Original guide, unchanged')}<br>Photo: ${link(trip.photoSource,trip.photoCredit)} · ${link('https://unsplash.com/license','Unsplash license')}</footer></main>`;
  document.getElementById('lock').addEventListener('click',()=>{ticketKey=null;for(const url of ticketUrls.values())URL.revokeObjectURL(url);ticketUrls.clear();trip=null;app.replaceChildren();app.hidden=true;gate.hidden=false;document.getElementById('password').focus();});
  document.getElementById('print').addEventListener('click',()=>window.print());
  app.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{activeView=b.dataset.view;render();document.getElementById('tab-'+activeView).focus();}));
  app.querySelectorAll('[data-day]').forEach(b=>b.addEventListener('click',()=>{activeDay=Number(b.dataset.day);render();document.getElementById('day-tab-'+activeDay).focus();}));
  app.querySelectorAll('[data-ticket]').forEach(b=>b.addEventListener('click',()=>openTicket(b)));
  app.querySelectorAll('[data-check]').forEach(c=>c.addEventListener('change',()=>{c.checked?sessionChecks.add(c.dataset.check):sessionChecks.delete(c.dataset.check);try{localStorage.setItem('paris-guide-checks-v1',JSON.stringify([...sessionChecks]));}catch{}updateProgress();}));
  app.querySelectorAll('[role=tablist]').forEach(list=>list.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const buttons=[...list.querySelectorAll('[role=tab]')],i=buttons.indexOf(e.target);if(i<0)return;e.preventDefault();let j=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[j].click();}));updateProgress();
}
function updateProgress(){
  if(!trip)return;const items=trip.reference.actionItems,remaining=ids=>items.filter(a=>ids.includes(a.id)&&!isDone(a)).length;
  const urgent=remaining(checklistGroups[0].ids),el=document.getElementById('check-progress');
  if(el)el.textContent=`${urgent?`${urgent} urgent item${urgent===1?'':'s'} remaining`:'All urgent items complete'} · ${items.filter(isDone).length} of ${items.length} preparation items complete`;
  app.querySelectorAll('[data-group-progress]').forEach(el=>{const group=checklistGroups.find(g=>g.key===el.dataset.groupProgress);if(group){const count=remaining(group.ids);el.textContent=count?`${count} remaining`:'Complete';}});
}

async function openTicket(button){
 const booking=trip?.bookings?.find(b=>b.id===button.dataset.ticket),key=ticketKey;
 if(!booking||!key)return;
 const notice=document.getElementById('ticket-status-'+booking.id);
 const preview=button.dataset.mode==='view'?window.open('about:blank','_blank'):null;
 if(preview){preview.opener=null;preview.document.title='Opening tickets';preview.document.body.textContent='Opening your ticket PDF…';}
 button.disabled=true;notice.textContent='Opening original ticket PDF…';
 try{
  let url=ticketUrls.get(booking.id);
  if(!url){
   if(!/^tickets-[0-9]+\.bin$/.test(booking.encryptedFile))throw Error('Invalid ticket path');
   const response=await fetch(booking.encryptedFile,{cache:'no-store'});if(!response.ok)throw Error('Download failed');
   const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(booking.iv)},key,await response.arrayBuffer());
   const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',plain)),x=>x.toString(16).padStart(2,'0')).join('');
   if(hash!==booking.sha256||new TextDecoder().decode(plain.slice(0,5))!=='%PDF-')throw Error('Ticket check failed');
   if(ticketKey!==key){preview?.close();return;}
   url=URL.createObjectURL(new Blob([plain],{type:'application/pdf'}));ticketUrls.set(booking.id,url);
  }
  if(preview){preview.location.href=url;notice.textContent='Opened the original four-ticket PDF in a new tab.';}
  else{const a=document.createElement('a');a.href=url;a.download=booking.downloadName;document.body.append(a);a.click();a.remove();notice.textContent='Download requested. Check your device’s Downloads or Files app and open it before traveling.';}
 }catch(error){preview?.close();notice.textContent='Could not open this ticket. Check your connection, unlock the guide again, or use the official order account link.';}
 finally{button.disabled=false;}
}
