'use strict';
const gate=document.getElementById('gate'), app=document.getElementById('app'), form=document.getElementById('unlock'), statusEl=document.getElementById('gate-status');
let trip=null, activeDay=0, activeView='days', sessionChecks=new Set();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const euros=v=>typeof v==='number'?new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(v):'See options';
const safeUrl=u=>{try{const x=new URL(u);return ['https:','http:'].includes(x.protocol)?x.href:'#';}catch{return '#';}};
const link=(u,label,cls='')=>`<a class="${cls}" href="${esc(safeUrl(u))}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;
const sourceLinks=urls=>`<div class="stop-links">${[...new Set(urls||[])].map((u,i)=>link(u,i===0?'Official / booking page':`Source ${i+1}`)).join('')}</div>`;
const mapLink=place=>link('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(place),'Open map');
const journeyLink=(from,to)=>link('https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(from)+'&destination='+encodeURIComponent(to)+'&travelmode=transit','Transit directions');
const paras=t=>String(t||'').split('\n').map(x=>`<p>${esc(x)}</p>`).join('');
const decode=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
form.addEventListener('submit',async e=>{
  e.preventDefault();const input=document.getElementById('password'),button=document.getElementById('unlock-button');button.disabled=true;statusEl.textContent='Opening your guide…';
  try{
    if(!globalThis.crypto?.subtle)throw new Error('secure');
    const response=await fetch('payload.json',{cache:'no-store'});if(!response.ok)throw new Error('network');
    const payload=await response.json();const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(input.value),'PBKDF2',false,['deriveKey']);
    const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:decode(payload.salt),iterations:payload.iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['decrypt']);
    const plaintext=await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(payload.iv)},key,decode(payload.data));
    trip=JSON.parse(new TextDecoder().decode(plaintext));input.value='';statusEl.textContent='';
    const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
    const matched=trip.days.findIndex(d=>d.date===today);activeDay=matched<0?0:matched;
    try{sessionChecks=new Set(JSON.parse(localStorage.getItem('paris-guide-checks-v1')||'[]'));}catch{sessionChecks=new Set();}
    render();gate.hidden=true;app.hidden=false;document.getElementById('app-title').focus();
  }catch(error){trip=null;statusEl.textContent=error.message==='secure'?'Open the HTTPS website in a current browser to unlock.':error.message==='network'?'The guide could not load. Check your connection and try again.':'That password did not open the guide. Please try again.';}finally{button.disabled=false;}
});
function stopHtml(s,index,day){return `<article class="stop"><time>${esc(s.time)}</time><div class="stop-card"><h3>${esc(s.title)}</h3>${paras(s.body)}${s.transfer?`<p class="transfer">${esc(s.transfer)}</p>`:''}<div class="stop-links">${s.place?mapLink(s.place):''}${s.url?link(s.url,'Details / tickets'):''}${s.place&&index===0?journeyLink(trip.home,s.place):''}</div></div></article>`;}
function dayHtml(d){return `<div class="day-layout"><div><div class="day-header"><span class="eyebrow">${esc(d.short)} · ${esc(d.leave)}</span><h2>${esc(d.title)}</h2><p>${esc(d.theme)}</p><div class="stats"><span>${esc(d.pace)}</span><span>${esc(d.walking)}</span></div></div><div class="timeline">${d.stops.map((s,i)=>stopHtml(s,i,d)).join('')}</div></div><aside><section class="side-card accent"><h3>Before you set off</h3><ul>${d.advice.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="side-card"><h3>If something changes</h3>${paras(d.fallback)}</section><section class="side-card"><h3>Weather plan</h3>${paras(d.weather)}</section><section class="side-card"><h3>Home base</h3><p>${esc(trip.home)}</p>${mapLink(trip.home)}<p class="small">All times here are Paris local. Check live directions before leaving.</p></section></aside></div>`;}
function ticketHtml(t){return `<article class="detail-card"><div class="ticket-top"><div><span class="tag">${esc(t.date||'Flexible')}${t.time?' · '+esc(t.time):''}</span><h3>${esc(t.name)}</h3></div><div class="price">${euros(t.familyPrice)}<small>family of four</small></div></div><p><strong>${esc(t.recommended)}</strong></p><p>${esc(t.availability)}</p><p><strong>Entry:</strong> ${esc(t.reservation)}</p><p><strong>Queues:</strong> ${esc(t.queueBenefit)}</p><p class="small">${esc(t.risk)}</p>${t.alternatives?.length?`<details><summary>Compare alternatives</summary>${t.alternatives.map(a=>`<p><strong>${esc(a.name)}${a.familyPrice!==null&&a.familyPrice!==undefined?' · '+euros(a.familyPrice):''}</strong><br>${esc(a.status)}</p>`).join('')}</details>`:''}${sourceLinks(t.sourceUrls)}</article>`;}
function foodHtml(f){return `<article class="detail-card"><span class="tag">${esc(f.noEggConfidence)}</span><h3>${esc(f.name)}</h3><p class="meta">${esc(f.address)}</p><p><strong>Order:</strong> ${esc(f.signatureChoices)}</p><p><strong>Hours:</strong> ${esc(f.hours)}</p><p><strong>Budget:</strong> ${esc(f.price)}</p>${f.reservations?`<p><strong>Planning:</strong> ${esc(f.reservations)}</p>`:''}<p class="small">${esc(f.basis||'')} ${esc(f.caveats)}</p><div class="stop-links">${mapLink(f.address)}${f.officialUrl?link(f.officialUrl,'Restaurant website'):''}</div>${sourceLinks(f.sourceUrls)}</article>`;}
function facts(rows){return `<dl class="facts">${rows.map(([a,b])=>`<dt>${esc(a)}</dt><dd>${esc(b)}</dd>`).join('')}</dl>`;}
function sourceNotes(text){return esc(text).replace(/https?:\/\/[^\s<>"&]+/g,u=>{const clean=u.replace(/[).,;]+$/,'');return `<a href="${clean}" target="_blank" rel="noopener noreferrer">${clean}</a>${u.slice(clean.length)}`;});}
function render(){const r=trip.reference;app.innerHTML=`
  <header class="topbar"><span class="brand">PARIS / EN FAMILLE</span><div class="top-tools">${link(trip.wanderlog,'Open Wanderlog')}<button id="print">Print / save PDF</button><button id="lock">Lock</button></div></header>
  <main class="shell"><section class="intro"><div><span class="eyebrow">${esc(trip.dates)}</span><h1 id="app-title" tabindex="-1">${esc(trip.title)}</h1><p>${esc(trip.intro)}</p><div class="pills"><span class="pill">${esc(trip.family)}</span><span class="pill">${esc(trip.diet)}</span></div></div><img src="${esc(trip.hero)}" alt="Eiffel Tower beside the Seine in Paris" width="700" height="360"></section>
  <nav class="section-tabs" aria-label="Guide sections" role="tablist">${[['days','Day by day'],['tickets','Tickets & prices'],['checklist','To book & prepare'],['food','Eat egg-free'],['travel','Stay & transport'],['research','Sources & decisions']].map(([id,name])=>`<button id="tab-${id}" role="tab" aria-controls="view-${id}" aria-selected="${activeView===id}" data-view="${id}">${name}</button>`).join('')}</nav>
  <section id="view-days" class="view" role="tabpanel" aria-labelledby="tab-days" ${activeView!=='days'?'hidden':''}><div class="notice">${esc(trip.alert)}</div><nav class="days" aria-label="Choose a day" role="tablist">${trip.days.map((d,i)=>`<button class="day-tab" id="day-tab-${i}" role="tab" aria-controls="day-content" data-day="${i}" aria-selected="${i===activeDay}"><strong>${esc(d.short)}</strong><span>${esc(d.name)}</span></button>`).join('')}</nav><div id="day-content" role="tabpanel" aria-labelledby="day-tab-${activeDay}">${dayHtml(trip.days[activeDay])}</div><div class="print-only">${trip.days.map(dayHtml).join('')}</div></section>
  <section id="view-tickets" class="view" role="tabpanel" aria-labelledby="tab-tickets" ${activeView!=='tickets'?'hidden':''}><h2>The right ticket for each stop</h2><p>Prices below apply to your four travelers. Published prices and live quotes are distinguished; no ticket has been purchased.</p><div class="budget"><div><span>Selected Paris + Versailles sights</span><strong>${euros(trip.budget.attractions)}</strong></div><div><span>Giverny day including travel</span><strong>${euros(trip.budget.giverny)}</strong></div><div><span>City passes + two airport taxis</span><strong>${euros(trip.budget.cityTransport)}</strong></div></div><div class="notice">${esc(trip.budget.note)}</div><div class="grid">${r.tickets.map(ticketHtml).join('')}</div></section>
  <section id="view-checklist" class="view" role="tabpanel" aria-labelledby="tab-checklist" ${activeView!=='checklist'?'hidden':''}><h2>Book in this order</h2><p>Tick items after you finish them. Checkmarks stay on this device; they do not reserve anything or sync with your family.</p><div id="check-progress" class="progress" role="status"></div><div class="checks">${r.actionItems.map(a=>`<label class="check"><input type="checkbox" data-check="${esc(a.id)}" ${sessionChecks.has(a.id)?'checked':''}><span><span class="tag">${esc(a.urgency)}</span><strong>${esc(a.title)}</strong><p>${esc(a.detail)}</p>${sourceLinks(a.sourceUrls)}</span></label>`).join('')}</div></section>
  <section id="view-food" class="view" role="tabpanel" aria-labelledby="tab-food" ${activeView!=='food'?'hidden':''}><h2>Good food, without eggs</h2><div class="notice"><p>${esc(trip.dietExplanation)}</p><p class="diet-phrase">${esc(trip.dietPhrase)}</p></div><p>Fully vegan places are the easiest choices. For mixed or vegetarian kitchens, order a specifically vegan dish or ask staff to confirm ingredients. Prices are menu observations or clearly marked estimates, not table quotes.</p><div class="food-grid">${[...r.restaurants,...r.bakeriesAndFamousCafe].map(foodHtml).join('')}</div></section>
  <section id="view-travel" class="view" role="tabpanel" aria-labelledby="tab-travel" ${activeView!=='travel'?'hidden':''}><h2>Your stay & getting around</h2><div class="grid"><article class="detail-card wide"><h3>Your apartment</h3>${facts(trip.travel.lodging)}<div class="actions">${mapLink(trip.home)}${link('https://www.airbnb.com/trips','Open Airbnb trips','button')}</div></article><article class="detail-card"><h3>Arrival · September 14</h3>${facts(trip.travel.arrival)}</article><article class="detail-card"><h3>Departure · September 19</h3>${facts(trip.travel.departure)}</article>${r.transit.map(t=>`<article class="detail-card"><h3>${esc(t.name)}</h3><p>${esc(t.description)}</p><p><strong>Set up:</strong> ${esc(t.setup)}</p><p><strong>Choice:</strong> ${esc(t.decision)}</p><p class="small">${esc(t.caveats)}</p>${sourceLinks(t.sourceUrls)}</article>`).join('')}<article class="detail-card wide"><h3>Small things that help</h3><p>Keep passport copies and tickets available offline; carry the original ID for age discounts and membership cards. Use a contactless card and a little cash for small purchases. France uses 230V Type E sockets; check your device charger rating and bring suitable adapters. Keep bags closed on the Métro and around busy attractions.</p><p>Emergency number: 112. For flight, rail or weather disruption, recheck the operator’s live status before setting off. Carry water, a light jacket and comfortable shoes; the apartment and several attractions have stairs.</p></article></div></section>
  <section id="view-research" class="view" role="tabpanel" aria-labelledby="tab-research" ${activeView!=='research'?'hidden':''}><h2>Why this route works</h2><div class="side-card"><ul>${trip.planningNotes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul></div><h3>Useful alternatives that did not make the main route</h3><div class="grid">${r.exclusions.map(x=>`<article class="detail-card"><h4>${esc(x.name)}</h4><p>${esc(x.reason)}</p>${sourceLinks(x.sourceUrls)}</article>`).join('')}</div><h3>Source record</h3><p>Research checked ${esc(trip.checked)}. Each ticket, restaurant and transport card links to its sources. The expandable notes preserve the fuller comparison and live-check details; the day-by-day guide above reflects the latest corrections.</p><p>${link(r.articleInfluence.url,'Your suggested Dangerous Business article')} · ${esc(r.articleInfluence.summary)}</p>${trip.research.map(n=>`<details><summary>${esc(n.title)}</summary><div class="raw-note">${sourceNotes(n.text)}</div></details>`).join('')}<details><summary>About the password protection</summary><p>The public site contains encrypted itinerary data. The browser derives a key from your password and decrypts the guide locally; the password and decrypted trip are not saved by the guide. The device stores only checklist item IDs. Lock or close this tab when finished on a shared device. Anyone with the password can read the full itinerary. Printing or saving a PDF creates an unencrypted copy.</p>${link('https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveKey','Web Crypto documentation')} · ${link('https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site','GitHub Pages hosting')}</details></section>
  <footer class="footer">Research checked ${esc(trip.checked)} · ${link(trip.wanderlog,'New private Wanderlog plan')} · ${link(trip.original,'Original guide, unchanged')}<br>Photo: ${link(trip.photoSource,trip.photoCredit)} · ${link('https://unsplash.com/license','Unsplash license')}</footer></main>`;
  document.getElementById('lock').addEventListener('click',()=>{trip=null;app.replaceChildren();app.hidden=true;gate.hidden=false;document.getElementById('password').focus();});
  document.getElementById('print').addEventListener('click',()=>window.print());
  app.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{activeView=b.dataset.view;render();document.getElementById('tab-'+activeView).focus();}));
  app.querySelectorAll('[data-day]').forEach(b=>b.addEventListener('click',()=>{activeDay=Number(b.dataset.day);render();document.getElementById('day-tab-'+activeDay).focus();}));
  app.querySelectorAll('[data-check]').forEach(c=>c.addEventListener('change',()=>{c.checked?sessionChecks.add(c.dataset.check):sessionChecks.delete(c.dataset.check);try{localStorage.setItem('paris-guide-checks-v1',JSON.stringify([...sessionChecks]));}catch{}updateProgress();}));
  app.querySelectorAll('[role=tablist]').forEach(list=>list.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const buttons=[...list.querySelectorAll('[role=tab]')],i=buttons.indexOf(e.target);if(i<0)return;e.preventDefault();let j=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[j].click();}));updateProgress();
}
function updateProgress(){const el=document.getElementById('check-progress');if(el&&trip)el.textContent=`${trip.reference.actionItems.filter(a=>sessionChecks.has(a.id)).length} of ${trip.reference.actionItems.length} preparation items complete`;} 
